tasks:
  - name: Create venv
    before: |
      python3 -m venv /workspace/hyper-connect-py/venv
      gp sync-done kitty
      clear
  - name: venv
    before: |
      gp sync-await kitty
      source venv/bin/activate
      gp sync-done meow
      curl -sSL https://install.python-poetry.org | python3 -
      poetry install
      pre-commit install
      bash .git/hooks/pre-commit
      echo 'Heres your virtual environment named venv.  Install deps here.'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
