tasks:
  - name: Create venv
    before: |
      python3 -m venv /workspace/hyper-connect-py/venv
      gp sync-done kitty
      clear
  - name: venv
    before: |
      gp sync-await kitty
      source venv/bin/activate
      gp sync-done meow
      curl -sSL https://install.python-poetry.org | python3 -
      poetry install
      pre-commit install
      bash .git/hooks/pre-commit
      echo '**************************************************************************'
      echo '***                                                                    ***'
      echo '***  Integration tests and examples depend on hyper app and services.  ***'
      echo '***              https://docs.hyper.io/applications                    ***'
      echo '***                https://docs.hyper.io/app-keys                      ***'
      echo '***      Be sure you have an environment variable named HYPER.         ***'
      echo '***      Set the HYPER value to a hyper app connection string.         ***'
      echo '***              See the REAMDME.md for more details                   ***'
      echo '***                                                                    ***'
      echo '**************************************************************************'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
